'use client';
import {useEffect,useState} from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
type Request={id:number,title:string,details:string,status:string,scheduledFor:string|null};
type User={id:number,username:string};
const API='http://localhost:8080/api';
export default function Home(){
 const [logged,setLogged]=useState(false),[username,setUsername]=useState('demo'),[password,setPassword]=useState('demo'),[error,setError]=useState('');
 const [list,setList]=useState<Request[]>([]),[users,setUsers]=useState<User[]>([]),[filter,setFilter]=useState(''),[title,setTitle]=useState(''),[details,setDetails]=useState(''),[date,setDate]=useState('');
 const load=()=>{fetch(`${API}/requests${filter?`?status=${filter}`:''}`).then(r=>r.json()).then(setList);fetch(`${API}/users`).then(r=>r.json()).then(setUsers)};
 useEffect(()=>{if(logged)load()},[logged,filter]);
 if(!logged)return <main className="mx-4 mt-12 flex max-w-sm flex-col gap-4 rounded bg-white p-6 shadow sm:mx-auto sm:mt-24 sm:p-8"><h1 className="text-2xl font-bold">Service Requests</h1><p className="text-sm">Demo account: demo / demo</p><input aria-label="Username" placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)}/><input aria-label="Password" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="text-red-600">{error}</p>}<button onClick={async()=>{setError('');const r=await fetch(`${API}/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});if(r.ok)setLogged(true);else setError('Invalid username or password.')}}>Log in</button></main>;
 const add=async(e:React.FormEvent)=>{e.preventDefault();await fetch(`${API}/requests`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,details,scheduledFor:date||null})});setTitle('');setDetails('');setDate('');load()};
 return <main className="w-full p-4 sm:p-8"><h1 className="mb-6 text-3xl font-bold">Service Request Demo</h1><form onSubmit={add} className="mb-6 grid gap-3 rounded bg-white p-4 shadow sm:grid-cols-2 lg:grid-cols-4"><input required placeholder="Request title" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Details" value={details} onChange={e=>setDetails(e.target.value)}/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button>Add request</button></form><select className="mb-4" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option><option value="OPEN">Open</option><option value="COMPLETE">Complete</option></select><div className="grid items-start gap-6 md:grid-cols-2"><section className="min-w-0 space-y-3"><h2 className="text-xl font-bold">Requests</h2>{list.length===0&&<p className="rounded bg-white p-4 text-sm text-slate-600 shadow">No requests to display.</p>}{list.map(r=><article className="break-words rounded bg-white p-4 shadow" key={r.id}><b>{r.title}</b> <span className="text-sm">{r.status}</span><p>{r.details}</p><p>{r.scheduledFor||'Unscheduled'}</p><div className="mt-2 flex flex-wrap gap-2">{r.status==='OPEN'&&<button onClick={async()=>{await fetch(`${API}/requests/${r.id}/complete`,{method:'PATCH'});load()}}>Complete</button>}<button onClick={async()=>{await fetch(`${API}/requests/${r.id}`,{method:'DELETE'});load()}}>Remove</button></div></article>)}</section><section className="min-w-0 rounded bg-white p-4 shadow"><h2 className="mb-3 text-xl font-bold">Users</h2>{users.map(u=><p key={u.id}>{u.username}</p>)}</section><section className="col-span-full min-w-0 rounded bg-white p-4 shadow"><FullCalendar plugins={[dayGridPlugin]} initialView="dayGridMonth" height="auto" events={list.filter(r=>r.scheduledFor).map(r=>({title:r.title,date:r.scheduledFor!}))}/></section></div></main>;
}
